version: '3'

services:
  harvester_api:
    container_name: harvester_api
    restart: always
    build:
      context: ./api
    ports:
      - 8082:80
    env_file:
      - .env
  redis:
    image: redis:latest
    restart: always

  harvester_gpsd:
    container_name: harvester_gpsd
    restart: always
    build:
      context: ./gpsd
    devices:
      - "/dev/ttyACM0:/dev/ttyUSB0"
    ports:
      - 2948:2947